### ISSUE TITLE
Any plans for support of other Databases

### ISSUE THREAD

**Issue by jiaulislam** [davidjconnelly/trongate-framework#105]
Hi.  Greetings from Bangladesh. I was wondering if there will be any support for Other relational database like oracle as i have seen that in prerequisite in Maria DB. which can't be used in many enterprise Applications as existing all systems are in oracle already. 

TIA

**Comment by DaFa66** [comment]
Hi jiaulislam,

I think it would be a good idea to add other databases and I may have a go at myself if DC is too busy doing other things.

**Comment by cisnez** [comment]
Are you not using PDO?

PDO will work on 12 different database systems.

**Comment by davidjconnelly** [comment]
I was of the understanding that PDO worked with a bunch of different databases.  However, it's a topic that I'm not entirely up to speed with, if I'm being honest.

Many thanks to Dafa for looking into this.

While we wait on more data, I'd encourage you to check out this video on YouTube:

https://www.youtube.com/watch?v=DuB6UjEsY_Y 

It's the creator of PHP discussing why all of the PHP frameworks suck.  In the video, he specifically mentions databases and I think his perspective is one that the Trongate framework should remain in alignment with.  

Right now, we have a framework that smokes the competition on every benchmark known to humanity.  In order for that to continue, we sometimes have to say 'no' to perfectly good ideas.  So, whilst the request is legitimate, I'd appeal to you to come into this with an open mind.  I promise to do likewise.

**Comment by DaFa66** [comment]
I totally agree, Rasmus Lerdorf's explanation is perfect here: "all general purpose frameworks", like Laravel and Symfony bloat the whole process and basically just SUCK!  The way DC has designed Trongate is precise, and we can work with that to add more database support from the config so it's only defined ONCE and then we will be free to use PDO with no changes to the CRUD methods in the Model.

**Comment by jiaulislam** [comment]
@davidjconnelly thnx for your reply.  PDO will be good for some of apps of our and I'm hoping to migrate with those with PDO but as for our company heavily rely on Oracles Stored Procedures & Functions for those PDO will be a headache i guess. And as we have used OCI8 in php so i guess it should work with your framework as all I'm doing is core PHP thing.

**Comment by davidjconnelly** [comment]
Okay.  Well, you're gonna have to figure it out on your own, I'm afraid.  I can't add a wall of IFs for what appears to be a rare use case.
