### ISSUE TITLE
Undefined $template on line 130

### ISSUE THREAD

**Issue by jakecastelli** [davidjconnelly/trongate-framework#11]
When records are more than 10, then it will throw an error.

To quickly recreate the issue:

Use tg-desktop app:
1. create a new app
2. create a new module
3. create more than 10 records in your new module manage page

error: 
undefined $template on line 130 in engine/Pagination.php

**Comment by DaFa66** [comment]
great pick up Jake. I see others on the forum were having issues with this too when setting 'ILovePHP' to true and creating modules with more than 10 items

**Comment by davidjconnelly** [comment]
Okay.  It shouldn't be too difficult to fix.  As soon as I've finished SCA, I will look into this (probably within the next seven days).

I appreciate the bullet points.  Good explanation.  Thanks.
