### ISSUE TITLE
$this->_not_allowed_msg();  Undefined Method.

### ISSUE THREAD

**Issue by monxian** [davidjconnelly/trongate-framework#30]
In the trongate_tokens module. In the _validate_token() function  $this->_not_allowed_msg(); is an
undefined method. Looks like its called from the Api.php inside the engine.

**Comment by davidjconnelly** [comment]
Thank you for that!  I'll look into that shortly.

**Comment by davidjconnelly** [comment]
Is this still an issue?

**Comment by davidjconnelly** [comment]
It's okay.  It's fixed now.  Thank you for bringing this up.
