### ISSUE TITLE
Undefined constants

### ISSUE THREAD

**Issue by CRX3** [davidjconnelly/trongate-framework#32]
engine > Model.php
	line 19: DEBUG = Undefined constant

engine > tg_helpers > form_helper.php
	line 77: AUTOCOMPLETE = Undefined constant

**Comment by davidjconnelly** [comment]
Hi.  I had added this in response to a request.  Somebody wanted the ability to define the models test mode inside config.  However, regardless of how well or how poorly I've implemented this, I think it was a bad call.  So, thank you.  I will remove those lines immediately.
