### ISSUE TITLE
Define standard css rules

### ISSUE THREAD

**Issue by CRX3** [davidjconnelly/trongate-framework#33]
engine > tg_transferer > index.php
	line 123: define standard rule @keyframes
	line 134: define standard rule: animation-name, animation-duration, animation-iteration-count, animation-timing-function, animation-direction

**Comment by davidjconnelly** [comment]
Hi CRX3.  We meet again!  I'll level with you... I'm not too clued up on any of that.  If you'd like to do a pull request then I'll certainly be glad to bring in your suggestions for this.

**Comment by davidjconnelly** [comment]
Okay.  This is for some text that blinks and - as far as I can tell - it works.  If I have failed to define animations correctly then I'm 100% welcoming of any pull requests that might be made.  However, at the moment there are no such pull requests and the clock is ticking.  I have to move forward.  If you or anyone wants to submit a pull request to tweak the CSS then I'll be delighted to take any such tweaks on board.  In the meantime, we're gonna have to live with the thought that one of our CSS animations is not defined 'by the book'.
