### ISSUE TITLE
Model.php, function get_where_custom always showing query, ignoring value of  $debug

### ISSUE THREAD

**Issue by madkevo** [davidjconnelly/trongate-framework#40]
Hi David,
I saw you "fix" this on live stream, however you actually broke it. I'm not sure which issue this addressed so creating a new one.
In Model.php from 1.3.3025, at line 163 you need to put back the condition if ($this->debug == true) {
closing the curly bracket after $this->query_caveat);
Otherwise using get_where_custom will always print the queries out.

**Comment by davidjconnelly** [comment]
Okay.  Thanks for that.  I must confess I'm a little bit confused.  So, I've reverted back to where we were.  

Whatever the original bug was I have clearly failed to understand the nature of the problem.  So, if I may, I'm going to close this one and ask you to create a new issue request for whatever led us here in the first place.  Cheers!
