### ISSUE TITLE
Module relation (comma seperated identifier_column does not work in the same way as prev version)

### ISSUE THREAD

**Issue by vanHeerwaarden** [davidjconnelly/trongate-framework#42]
The new desktop app works great. I have my first question that has to do with the module relation. I like to use more columns in my dropdown.  

Working with the old desktop app I used the posibility to use more than one "identifier_column" comma separated and worked very well.

I am not sure if with the new desktop app we have an other method to do it, or that it also can added to the new desktop app or that it cannot added.

![image](https://user-images.githubusercontent.com/4414249/122680925-10dad600-d1f2-11eb-9fc4-6dd0c477d708.png)

Greatings Jerry

**Comment by davidjconnelly** [comment]
Yes, it's okay.  I knew about this one.  It's on the ol' to do list.  The whole desktop app has been rebuilt.  It'll be a few days before I get onto that.  Cheers for bringing it up though.  It's a legit issue.

**Comment by davidjconnelly** [comment]
This one should now be sorted.
