### ISSUE TITLE
Not forget in todo list: change MODULE DETAILS

### ISSUE THREAD

**Issue by vanHeerwaarden** [davidjconnelly/trongate-framework#43]
I looked writing your todo list and missed one item belonging at the end of the list. 

This is an item you already mentioned (and I appreciate very in the previous version).
Soon you'll be able to edit the different values from here. However, we're not quite there yet. Changes are happening daily and I appreciate your patience at this time. Cheers! - DC

![image](https://user-images.githubusercontent.com/4414249/122683389-1854ac00-d1ff-11eb-872f-31a30dbbc0e5.png)

**Comment by davidjconnelly** [comment]
Yes!  You're right.

Originally I had planned on leaving this one until after the launch.  However, if there are language issues and if this is something that is mission critical then I'd be glad to have this moved high up the priority list.

**Comment by davidjconnelly** [comment]
This should be sorted within the next week or so.  Currently dealing with a lot of issues, from design to doing videos, to the add.  Nevertheless, I want to assure you that I have not forgotten about this.  It's a good vibe.

**Comment by davidjconnelly** [comment]
Okay.  That should not be sorted for Module Relations.  Let me know if you experience any challenges.
