### ISSUE TITLE
Update engine

### ISSUE THREAD

**Issue by vanHeerwaarden** [davidjconnelly/trongate-framework#44]
For the early users of trongate some updates are easier to update when familiar with the new engine.
When by acident the engine is updated it's not easy to go back to the previous engine.

**Comment by davidjconnelly** [comment]
My friend... it's a price I have to pay.  The two desktop apps may look the same but I can assure you, they are completely different.  Every single line of code has been rewritten.  The new one is designed to be more compact and more easy to update.  The consequences of sticking with the 'old' desktop app are that every time an update happened then I'd have to compile for all three operating systems and get every single user to download and install again.  To me this is not acceptable.

We simply HAVE to take the hit.  I've been writing about this over at SCA for a long time.  I've even said that I'll be willing to personally help out if anyone has problems with a particular site.  

If there was an epidemic with early adopters who had challenges with older versions of the engine then I think it would be possible to write programme or script that automatically does all of the tweaks.  If this does turn out to be a major issue then I'd be willing to build such a thing - after the launch.

In the meantime, I'm afraid we _have_ to move forward.  I cannot juggle two systems at the same time.
