### ISSUE TITLE
Problem with Image Upload

### ISSUE THREAD

**Issue by mamalinio** [davidjconnelly/trongate-framework#45]
Maybe this has already been addressed but here goes
OS windows, Server Xampp and directory permissions looks fine, Trongate Pre-launch version while trying the image uploader

Uncaught Error: Call to undefined function imagecreatefrompng() in C:\xampp\htdocs\image_test\engine\Image.php:53 
Same for imagecreatefromjpeg

**Comment by DaFa66** [comment]
Make sure the GD module is loaded in php. There is another thread
explaining this and how to fix it too.

**Comment by mamalinio** [comment]
Ahhh yes my bad... I didn't see it was commented! Thanks!

**Comment by mamalinio** [comment]
Work great with GD module on!
