### ISSUE TITLE
Many to many relation not working associated sections nothing appears

### ISSUE THREAD

**Issue by vpsingh11** [davidjconnelly/trongate-framework#48]
![lecture_information_no relation](https://user-images.githubusercontent.com/87649460/126263693-1b9fbd9e-da0c-412c-8667-2bfe1917ad69.png)
![student_information_no relation](https://user-images.githubusercontent.com/87649460/126263705-8ecfb01e-9222-4e56-afbf-23f8ceefaa16.png)

I have created many to many module relation using desktop app but nothing appears in associated sections on show page.

**Comment by jitenders859** [comment]
![Screenshot 2021-07-20 at 11 01 38 AM](https://user-images.githubusercontent.com/41188075/126266982-d6f5d245-9d72-4a1a-96b4-183dca906440.png)

I have also tried doesn't create any additinal tables in database for many to many relations
windows and mac desktop app facing issues on both

**Comment by davidjconnelly** [comment]
Thank you.  That's now fixed.  With all new apps this should now work fine.

If you have an old app and you want to fix it, replace your 'module_relations' module with the one from the following GitHub repo:

https://github.com/davidjconnelly/module_relations 

Many thanks for bringing this up.

Talk soon,

DC
