### ISSUE TITLE
Updating admin password

### ISSUE THREAD

**Issue by monxian** [davidjconnelly/trongate-framework#51]
Validation rule for updating admin password fails. Rule calls for min 6 character and admin has 5.
Admin password can't be updated.

**Comment by davidjconnelly** [comment]
Well spotted!  That's now sorted.  Thank you so much.

**Comment by monxian** [comment]
I actually did a horrible job describing the bug. It's the username validation rule set that needs to have a min_length[5]. 
When you try to update the password for admin the form fails because  rule has a min_length[6] and admin has 5 letters in it.

Unless this is by design so you have to create a new admin.
