### ISSUE TITLE
Desktop app continuously load sometimes when creating image uploader (Windows)

### ISSUE THREAD

**Issue by vpsingh11** [davidjconnelly/trongate-framework#54]
![continously _loading](https://user-images.githubusercontent.com/87649460/126589316-ddfd82db-b240-430c-b307-52e60f5cce53.png)

Desktop app loads continuously when creating image uploader after closing and reopening it works.

**Comment by DaFa66** [comment]
Ah yes, I see what you mean... but it only seems to happen if you open the settings before you try and add the image uploader.

I tried to find the problem by putting the Desktop app in dev mode and discovered after opening the settings and closing it, then clicking on 'GENERATE IMAGE UPLOADER'

![image](https://user-images.githubusercontent.com/7813262/126988509-bd098177-de3e-4769-862e-330665a0b38b.png)

I see this in the terminal:
![image](https://user-images.githubusercontent.com/7813262/126988815-42c76c9b-86d5-4d5f-ac09-64c8685b53f8.png)

I'd say something is getting screwed up with the image settings and DC will need to look into this and fix the bug.

Good pick up though 👍

DC - this is happening on Windows, haven't tested it on Mac or Linux - if I find they are cool I'll let you know.

Cheers,
Si

**Comment by davidjconnelly** [comment]
Thank you for this.  Simon was right.  When closing the config screen it was messing with the settings.  I think we're good now.   Cheers!
