### ISSUE TITLE
url_string property not generating when using desktop app

### ISSUE THREAD

**Issue by vpsingh11** [davidjconnelly/trongate-framework#55]
![url_string](https://user-images.githubusercontent.com/87649460/126631231-886c87b7-572d-47ef-be63-970aa53b20c3.png)

I have created a module using trongate desktop app. All properties generated except url_string in database. When selecting url parameter.

**Comment by davidjconnelly** [comment]
Thank you for raising this.  The issue was being caused by a typo.  In the code generator I had said 'user_column' instead of 'url_column'.  That's now fixed and we should be good.  Thanks again!
