### ISSUE TITLE
Admin id hard coded into tg_admin_template.php

### ISSUE THREAD

**Issue by StephenMM1952** [davidjconnelly/trongate-framework#56]
Line 25 of tg_admin_template.php is currently hard coding the admin id into the url for the link to Update Your Account:
`<a href="<?= BASE_URL ?>trongate_administrators/create/1">`

So when you have more than 1 admin user it always tries to update admin user 1.

Change line 25 to: 
`<a href="<?= BASE_URL ?>trongate_administrators/create/<?= $data['my_admin_id']?>">`

**Comment by davidjconnelly** [comment]
Thank you so much.  That's outstanding!
