### ISSUE TITLE
Server Response 500 Internal Server Error

### ISSUE THREAD

**Issue by jitenders859** [davidjconnelly/trongate-framework#61]

**Comment by jitenders859** [comment]
![Screenshot 2021-08-08 at 5 55 58 PM](https://user-images.githubusercontent.com/41188075/128631917-e6cc259d-3d94-4dea-8ef2-6a16ff32093f.png)

I have trying to use api explorer but getting this issue 500 internal server error I have used trongate desktop app to generate the code

**Comment by davidjconnelly** [comment]
I am not able to reproduce that error.  I would need full instructions on how to reproduce that.  Also I can see that you have an error in your module name.  It says 'bookss'.  Shouldn't that be 'books'?
