### ISSUE TITLE
Pre-Launch Desktop App Glitch when attempting to Delete a Module

### ISSUE THREAD

**Issue by StephenMM1952** [davidjconnelly/trongate-framework#64]
With the Pre Launch version of the Trongate Desktop App, two minor observations - neither of which seriously gets in the way of progress but are nevertheless annoying and I thought you might like to fix them before launch:

1. Using the App to delete a Trongate Module. Click on Delete Module then Select Option to choose the module be deleted. The Text on the screen says:
"TO DELETE THE _**BOOKINGS**_ MODULE ..." presumably a leftover from an earlier project.

2. Having then selected the module for deletion, if you then happen to mis-type the word DELETE for example DELETR a window pops up and tells you to type the word 'delete'. Then dismiss the pop up by clicking OK but the app does not allow focus back to the text field so you have to RESET the app  and start again.

**Comment by davidjconnelly** [comment]
Thanks for that.  I have sorted both of those issues out.  Please note, the desktop app is using Electron and there may potentially be a caching issue with regards to the auto-focus thing.  Nevertheless, that should iron itself out.  Thanks for bringing this up.
