### ISSUE TITLE
View function not working set to private.

### ISSUE THREAD

**Issue by monxian** [davidjconnelly/trongate-framework#65]
Just spun up new app. The view function inside trongate.php is set to private. Kills the server with error 500.
Changed to public working again.

**Comment by delboy1978uk** [comment]
already fixed by the look of it https://github.com/davidjconnelly/trongate-framework/commit/4e26e20eda96fd7f038f94f8db2cec1ec5ddbb0c#diff-86487555b188ec28ce65c90dabad84b5a5d231d29cb9eec19b61bd264307f6f9

**Comment by davidjconnelly** [comment]
Thanks for that.  We are cool.  It's sorted.
