### ISSUE TITLE
Setting database DEBUG mode 

### ISSUE THREAD

**Issue by StephenMM1952** [davidjconnelly/trongate-framework#67]
In order to set debug mode on the database, engine/model.php needs to be edited. It would be safer and consistent with the advice not to modify engine files if this were to be moved to the config/database.php file.

**Comment by davidjconnelly** [comment]
I think it already has that functionality.

**Comment by StephenMM1952** [comment]
I can't find it.

**Comment by StephenMM1952** [comment]
New pull request created
