### ISSUE TITLE
Unable to edit the associated bridge tables on gui

### ISSUE THREAD

**Issue by monxian** [davidjconnelly/trongate-framework#7]
The paragraph element is display:none is set on all associated module views. Quick fix go into web inspector un-click display: none. While this does make the modal appear it still has no functionality

**Comment by monxian** [comment]
In the fetch function of associated modules is seems there is a duplicate of the one of the search tables. 
 ` associated_module_name.'.$identifier_column.' AS identifierColumn
`
fetch seems to work after I remove associated_module_name
`'.$identifier_column.' AS identifierColumn`

Still working on the populating the dropdown modal seems related to the sql query also

**Comment by davidjconnelly** [comment]
Hi.  I have uploaded a major update to the framework and I'm not sure if this issue is still relevant.  If I'm may, I'm going to close this one.  However, if it's still an issue then please re-open and I'll be right here for you.  Many thanks!
