### ISSUE TITLE
No way to add CORS headers

### ISSUE THREAD

**Issue by gstesq** [davidjconnelly/trongate-framework#74]
I couldn't find a way of adding CORS headers to the API to allow access from other domains - apart from manually adding it to the API in Engine. Is there another way to do this?

![image](https://user-images.githubusercontent.com/15643243/140878522-bbc63c92-cdbc-4472-a104-0fa299fc3f0a.png)

**Comment by davidjconnelly** [comment]
Hi.  You can create a before hook and add your header access statement to that.

**Comment by gstesq** [comment]
Perfect - thanks!
