### ISSUE TITLE
Can we add form_number to Trongate helpers.

### ISSUE THREAD

**Issue by monxian** [davidjconnelly/trongate-framework#75]
Form_numbers would be useful I think for form_helpers.php
Looks like we only need to copy form_input and change the function name and 
the return input to type="number"

and maybe adding input[type="number"] to the trongate.css

**Comment by davidjconnelly** [comment]
That's all taken care of.  It was a good suggestion.  

Do you want to get on the 'contributors' list?  You'll have to do some kind of pull request (not necessarily for this but for moving a comma or something).  It means you'll get the credit.

Many thanks for this.

**Comment by DaFa66** [comment]
Hi guys, no need to add extra input types to the form helper.

We recently had a request for a similar issue on the [forum](https://ums.myds.me/phpbb/viewtopic.php?f=7&t=1074) where Dan was asking about a colour picker.  I suggested the below code snippet to use input type=color.  The same can be applied for other input types.

`<?php
echo form_open($form_location);
echo form_label('Colour (optional)');
$html = form_input('colour', $colour, array("placeholder" => "Enter Colour"));
// modify returned html to include a colour picker
$html = str_replace(' type="text" ', ' type="color" ', $html);
echo $html;` 

I've also left a comment in the [docs](https://trongate.io/docs_m/information/the-form-helper)

Ciao,
Simon
