### ISSUE TITLE
config/themes.php missing when upgrading from 1.3.3021 to 1.3.3031

### ISSUE THREAD

**Issue by madkevo** [davidjconnelly/trongate-framework#78]
I upgraded the TG frameswork from 1.3.3021 to 1.3.3031 using Trongate desktop app (Windows) 1.0.003

I then received Server error 500 from Apache running on Ubuntu:
The error log from apache showed this:
[Tue Jan 18 17:05:10.587411 2022] [php7:warn] [pid 76662] [client 192.168.xxx.xxx:1300] PHP Warning:  require_once(../config/themes.php): failed to open stream: No such file or directory in /home/tg/app/engine/bootstrap.php on line 7
[Tue Jan 18 17:05:10.587875 2022] [php7:error] [pid 76662] [client 192.168.xxx.xxx:1300] PHP Fatal error:  require_once(): Failed opening required '../config/themes.php' (include_path='.:/usr/share/php') in /home/tg/app/engine/bootstrap.php on line 7

Created themes.php in /config, populated it from config/themes.php from GitHub https://github.com/davidjconnelly/trongate-framework and then it was ok again

I don't think this was a write permission thing when the TG desktop app updated the files as license.txt and the other files updated ok.

**Comment by davidjconnelly** [comment]
Hello there,

I apologise for that.  What happens is, when you do an update - using the Desktop App - it swaps out your engine folder.  Nothing more.

So, I'm afraid you're gonna have to manually do a little bit of tweakery in this instance.  I apologise if that's not ideal but you have got on board at ground zero and for those who are early adopters there are a few moments like this, as we find out feet.

My advice is:

* download / create an entirely new app
* generate one module for the new app (just a simple to-do list manager or something)
* copy the ENTIRE config directory from the new (test) app into your existing app
* replace the config settings as required
* (I have done some work on the CSS and JS files inside the public folder, so...) create a backup of your existing public folder on the site you're working on
* copy the public folder from the new app and paste into the app you're working on
* add files and code, as required, to bring your new public folder in line with how your app was

Once again, I apologise if none of this is perfect.  I'm right here if you need me.  Best of luck.

DC
