### ISSUE TITLE
Model.php insert() method fails on column names matching database reserved words

### ISSUE THREAD

**Issue by gavincox** [davidjconnelly/trongate-framework#79]
A help Bar post identified an issue when using specific column names (database reserved words) causing a fatal error.
The solution surrounds each column name with backticks to identify each item as a column name in the final query.

Suggested fix is as follows:

engine/Model.php ~ line 403:

`$sql.= implode(", ", array_keys($data)).')';`

can be replaced with:

$sql.= '\`'.implode("\`, \`", array_keys($data)).'\`)';

**Comment by gavincox** [comment]
Pull request #81 submitted as suggested by @DaFa66

**Comment by DaFa66** [comment]
Hi DC, please see help-bar https://trongate.io/help_bar/thread/k9kQmZVVRBMX where user was getting an update query error.  He had column names using reserved key words that would trip Trongate up.  Gavin adding the back-ticks will eliminate this, so suggest he create this pull request :)
