### ISSUE TITLE
Trying to use the Desktop App

### ISSUE THREAD

**Issue by nturton240** [davidjconnelly/trongate-framework#83]
I had the desktop app working fine on my PC for a while.  Now every time I try to make a new app, I get just past the enter database connection details and I get the following error.

"typeerror: conn.query is not a function"

I have no idea what has happened.  I have even re-downloaded the desktop app and it still does it.

Update:

Even deleting the trongate folder in the appdata folder has not fixed this issue.

**Comment by keilanknight** [comment]
In almost all cases this means your database is not running. The desktop
app is going to want to connect to MySQL to generate the database and
tables, so they need to be running first!! If they are running then check
you have the right port number, username and password etc. defined when you
enter database connection details.
