### ISSUE TITLE
TypeError: con.query is not a function

### ISSUE THREAD

**Issue by KevinBlakeLopez** [davidjconnelly/trongate-framework#86]
![image](https://user-images.githubusercontent.com/80014258/161439959-fae319b3-84b2-43fa-a775-0daffb3d3a88.png)

Hello David,
I installed the Trongate Desktop app on my 2015 Macbook Air with MacOS Big Sur.  I have XAAMP installed.  I did not use PHPmyAdmin to manually create a database before attempting to create an app.  Instead, I went straight to the Trongate Desktop app and I had the TypeError pop up.  Not sure why this is happening or how to fix.
Thanks,
Kevin

**Comment by davidjconnelly** [comment]
Hi Kevin,

I too have a 2015 MacBook Air!

Whatever it is, I think your two issues are related.  I don't know what it is to be honest.  I think Simon solved this one previously.  So, perhaps you could try the Help Bar.

Of course, if you join the Trongate Fellowship for the price of a McDonald's Happy Meal, you can enjoy one on one support via Skype from the guy who made the framework.  Screen sharing and everything!  Oooh yeah!  Wouldn't it be a wonderful world if things like that actually happened?

Come on Kevin boy.  You know you want to!

**Comment by KevinBlakeLopez** [comment]
David,
Yes you are correct.  I definitely want to!  Hahaha.  I will join right now.
Kevin

**Comment by KevinBlakeLopez** [comment]
Hmm, I'm trying to become a member and I've tried several different ways
using PayPal and also manually entering a debit card, but then this is
happening each time:
[image: image.png]

**Comment by davidjconnelly** [comment]
YAAAASSSS!!!!  Whatever you did appears to have worked.

Welcome to the revolution, my friend!  

Add me on Skype and let's get you sorted as a priority.

My Skype username is david.webguy

**Comment by KevinBlakeLopez** [comment]
okay will do.  I won't be available today as I'm moving into a new
apartment, but I am certainly looking forward to connecting with you.
Thanks David!

Btw, have you ever considered using Signal app for communication instead
of Skype?  I'm a bit paranoid about privacy and don't trust big tech but
I'll certainly use Skype to talk with you as that is what you are currently
using.  Personally, I'm planning to ditch this gmail account at some point
and just use my protonmail account instead.

Kevin

**Comment by davidjconnelly** [comment]
I've never heard of it but it's a cool name.  I think it's inevitable that I'll ditch big tech at some point.  The idea of having a life free from Google and the gang certainly sounds good doesn't it?

Anyway, just add me whenever is good for you.  If I'm not around or if I don't answer then it's either because I'm with a client or I'm recording a video for Speed Coding Academy.

I generally work massive hours these days so I'll be around and I'm sure you won't have any major difficulties.

Many thanks again, Kevin.

**Comment by DaFa66** [comment]
Oh, such bonding - love it 🥇 

Kevin, looks to me like you don't have PHP running, what stack are you using?

Xampp on Windows looks like this:
![image](https://user-images.githubusercontent.com/7813262/161756186-a3e7ab4a-3d3c-46f9-a42f-bbcb2ef1c9c9.png)

localhost:
![image](https://user-images.githubusercontent.com/7813262/161756389-7980e630-cfdc-4117-a45d-6a6d15619dbd.png)

**Comment by DaFa66** [comment]
By the way, DC, could you add a 'Pay whatever makes you feel good' option (level2) on the 'The Trongate Fellowship' join page?

$2.50US/p/m isn't enough for likes of Geir or me to join 😉💰

**Comment by davidjconnelly** [comment]
Hi Kevin,

I'm assuming we've solved this one.  I'll be glad to meet you on Skype again if you are having issues.  Right here for you.  Cheers!

DC

**Comment by KevinBlakeLopez** [comment]
So I believe I may have registered for the fellowship twice as I didn't
believe it went through the first time - once through
***@***.*** and then a second time through
***@***.***  Is that correct?  If so I'll just get a
refund for the second email.
Thanks,
Kevin
