### ISSUE TITLE
when you remove a module, the li of the dynamic_nav doesn't disappear

### ISSUE THREAD

**Issue by gdbaron** [davidjconnelly/trongate-framework#87]
Hi David, when you delete a module, it deletes folders, files and everything perfect, but the li of the dynamic_nav doesn't disappear. Thanks.

**Comment by davidjconnelly** [comment]
Perfectly 100% legitimate.  Thank you.  I agree.  

However, that's not really an issue.  It's just a feature that has not been added.  It may be added in the future though.  

Thanks!
