### ISSUE TITLE
Custom Validation Callback_ does not work

### ISSUE THREAD

**Issue by yashpatel7007** [davidjconnelly/trongate-framework#88]
Hello DC,

Custom Validation Callback_ functions do not get triggered if forms current url / endpoint and form action='URL' / endpoint is same. However other set_rules() definitions are working fine.

Please look into it.

**Comment by DaFa66** [comment]
Works fine for me.  Please see help bar at https://trongate.io

**Comment by yashpatel7007** [comment]
> Works fine for me. Please see help bar at https://trongate.io

Issue is already raised over there, please have a look https://trongate.io/help_bar/thread/9rsXRJ7SU8P6

**Comment by DaFa66** [comment]
As far as I'm concerned, there is no issue.
