### ISSUE TITLE
delete button on admin item show page

### ISSUE THREAD

**Issue by andymlr** [davidjconnelly/trongate-framework#9]
EDIT: *THIS IS RELATED TO THE TRONGATE APP*

i thought i might share this suggestion of improving the delete button that you see on every items show page on the admin panel.

Right now when modules have picture uploaders you can only delete the pictures by clicking on the delete button of the picture uploader card, which is totally fine. But when you want to delete the whole item, then it leaves the directory together with the picture inside your project.

This will obviously fill up your project with unused pictures which will have an impact on host/storage costs.
It can get very unmanageable on a big website really quick, so i thought this would be something that we need to fix.

With the help of Jason aka "codefire" i improved the delete function to delete the directories together with the pictures inside them if there are any.

I don't consider the code perfect, but it does the job perfectly.

Please tell me what you think of it.

http://ums.myds.me/phpbb/viewtopic.php?p=2310&sid=2174017500ed57f6bebee8489c7065ac#p2310

Cheers, 
Andy

```
function delete_images($module_name, $record_id) {
        $picture_directory_paths[] = [];
        $picture_directory_paths[] = APPPATH . 'public/'. $module_name .'_pics/'. $record_id . '/';
        $picture_directory_paths[] = APPPATH . 'public/'. $module_name .'_pics_thumbnails/'. $record_id . '/';
        $picture_directory_paths[] = APPPATH . 'public/'. $module_name .'_pictures/'. $record_id . '/';

        foreach ($picture_directory_paths as $picture_directory_path) {
            if (is_dir($picture_directory_path)) {

                $pictures = scandir($picture_directory_path);

                foreach ($pictures as  $pic) {

                   $full_path = $picture_directory_path . $pic;
                   unlink($full_path);

                }

            rmdir( $picture_directory_path);
            }
        }
        
    }

    function submit_delete() {
        $this->module('security');
        $this->security->_make_sure_allowed();

        $submit = $this->input('submit', true);

        if ($submit == 'Submit') {
            $update_id = $this->url->segment(3);
            $module = $this->url->segment(1);

            if (!is_numeric($update_id)) {
                die();
            } else {
                $this->delete_images($module, $update_id);
                $data['update_id'] = $update_id;

                //delete all of the comments associated with this record
                $sql = 'delete from comments where target_table = :module and update_id = :update_id';
                $data['module'] = $this->module;
                $this->model->query_bind($sql, $data);

                //delete the record
                $this->model->delete($update_id, $this->module);

                //set the flashdata
                $flash_msg = 'The record was successfully deleted';
                set_flashdata($flash_msg);

                //redirect to the manage page
                redirect($module.'/manage');
            }
        }
    }
```

**Comment by Andrewsuares** [comment]
Good idea. It would be better to define the directory names suffix's as constants in the config file. If for some reason they were changed in the Picture_uploader_multi.php, the delete would not work.

_pics
_pics_thumbnails
_pictures

**Comment by Murrchik** [comment]
Thanks Andrew. That might probably be better.

**Comment by davidjconnelly** [comment]
Believe it or not, I think that there are scenarios where you might want to keep the picture directories.  An example would be a car leasing website that has purchased pictures for cars.  All of the cars have an ID variable that does not change (called a CAP ID).  This unit has been used since the seventies.  There is a hypothetical scenario whereby you could delete record details for a vehicle (in this example) but you may still want to keep the pictures that you've paid for.  Anyway, regardless of that, I think the suggestion is good.  However, I think that this is more of a feature request than a bug.  Very soon I'm going to be launching a discussion forum on the Trongate website with a feature request section.  Please do add this and any other feature requests you have onto that.
