### ISSUE TITLE
url_string doesn't work for non latin characters

### ISSUE THREAD

**Issue by webclubz** [davidjconnelly/trongate-framework#91]
Hi David! I want to mention this useful auto generated url_string doesn't work for non latin characters. It needs to transliterate somehow...

![transliterate](https://user-images.githubusercontent.com/16557633/174680189-bfd55ed9-32ee-4ab3-b9f5-ecbad1d7cae2.jpg)

**Comment by davidjconnelly** [comment]
I would try changing the language tag at the top of the source code.  Here's a full reference:

https://www.w3schools.com/tags/ref_language_codes.asp 

You may have to also change the database type.
