### ISSUE TITLE
[Feature] Installation method with composer

### ISSUE THREAD

**Issue by amm834** [davidjconnelly/trongate-framework#98]
The best DX for every PHP devs is to install framework through the composer. Why don't you give us a solution that uses composer?

**Comment by EpicDevNL** [comment]
I do not think the author of this framework is a big fan of composer.

**Comment by amm834** [comment]
May be. He should support for the composer, if he want 4k+ stars.

**Comment by davidjconnelly** [comment]
No thanks to Composer.
