### ISSUE TITLE
Is $helper defined anywhere?

### ISSUE THREAD

**Issue by avenirer** [davidjconnelly/trongate-framework#99]
https://github.com/davidjconnelly/trongate-framework/blob/6b9eec3fb057e87b9942fcdc89c99db11f51f018/engine/Trongate.php#L36

Just taking a quick look at the code, I don't se $helper defined inside the method.

**Comment by DaFa66** [comment]
I'd say it's legacy code when DC first wrote the framework
`    public function pagination($pagination_data) {
        require_once 'tg_helpers/' . $helper . '.php';
    }`
The Pagination class now lives in Pagination.php and not in the tg_helpers folder

**Comment by chr1974** [comment]
i think DaFA66 is right, the function in mention i guess was loading in helper classes for pagination in the early start. Now pagination is draw in Pagination.php on line 206. in the function:
`static public function draw_pagination($pagination_data)`

**Comment by davidjconnelly** [comment]
My original plan was to have helpers (to be activated) declared inside config.  Later on, I realised that the framework could still be fast even if we left all the helpers switched on.  So, Dafa is right.  

If you're willing to deal with that and then do a pull request then I'll be glad to accept.

**Comment by davidjconnelly** [comment]
Okay.  I'm going to take that part out.  Thanks for spotting this and letting us know.
